security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: plaintext  # Kadangi slaptažodis tikrinamas DB, hash nereikalingas
    providers:
        database_provider:
            id: App\Security\DatabaseUserProvider
    firewalls:
        main:
            lazy: true
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                target: /login
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/.*, roles: ROLE_USER }